/*
 * Strava API v3
 *
 * Strava API
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package strava

type MetaActivity struct {
	// The unique identifier of the activity
	Id int64 `json:"id,omitempty"`
}
