/*
 * Strava API v3
 *
 * Strava API
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package strava

type MetaAthlete struct {
	// The unique identifier of the athlete
	Id int32 `json:"id,omitempty"`
}
