/*
 * Strava API v3
 *
 * Strava API
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package strava

type ModelError struct {
	// The code associated with this error.
	Code string `json:"code,omitempty"`
	// The specific field or aspect of the resource associated with this error.
	Field string `json:"field,omitempty"`
	// The type of resource associated with this error.
	Resource string `json:"resource,omitempty"`
}
