/*
 * Strava API v3
 *
 * Strava API
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package strava
// ActivityType : An enumeration of the types an activity may have.
type ActivityType string

// List of ActivityType
const (
	ALPINE_SKI_ActivityType ActivityType = "AlpineSki"
	BACKCOUNTRY_SKI_ActivityType ActivityType = "BackcountrySki"
	CANOEING_ActivityType ActivityType = "Canoeing"
	CROSSFIT_ActivityType ActivityType = "Crossfit"
	E_BIKE_RIDE_ActivityType ActivityType = "EBikeRide"
	ELLIPTICAL_ActivityType ActivityType = "Elliptical"
	GOLF_ActivityType ActivityType = "Golf"
	HANDCYCLE_ActivityType ActivityType = "Handcycle"
	HIKE_ActivityType ActivityType = "Hike"
	ICE_SKATE_ActivityType ActivityType = "IceSkate"
	INLINE_SKATE_ActivityType ActivityType = "InlineSkate"
	KAYAKING_ActivityType ActivityType = "Kayaking"
	KITESURF_ActivityType ActivityType = "Kitesurf"
	NORDIC_SKI_ActivityType ActivityType = "NordicSki"
	RIDE_ActivityType ActivityType = "Ride"
	ROCK_CLIMBING_ActivityType ActivityType = "RockClimbing"
	ROLLER_SKI_ActivityType ActivityType = "RollerSki"
	ROWING_ActivityType ActivityType = "Rowing"
	RUN_ActivityType ActivityType = "Run"
	SAIL_ActivityType ActivityType = "Sail"
	SKATEBOARD_ActivityType ActivityType = "Skateboard"
	SNOWBOARD_ActivityType ActivityType = "Snowboard"
	SNOWSHOE_ActivityType ActivityType = "Snowshoe"
	SOCCER_ActivityType ActivityType = "Soccer"
	STAIR_STEPPER_ActivityType ActivityType = "StairStepper"
	STAND_UP_PADDLING_ActivityType ActivityType = "StandUpPaddling"
	SURFING_ActivityType ActivityType = "Surfing"
	SWIM_ActivityType ActivityType = "Swim"
	VELOMOBILE_ActivityType ActivityType = "Velomobile"
	VIRTUAL_RIDE_ActivityType ActivityType = "VirtualRide"
	VIRTUAL_RUN_ActivityType ActivityType = "VirtualRun"
	WALK_ActivityType ActivityType = "Walk"
	WEIGHT_TRAINING_ActivityType ActivityType = "WeightTraining"
	WHEELCHAIR_ActivityType ActivityType = "Wheelchair"
	WINDSURF_ActivityType ActivityType = "Windsurf"
	WORKOUT_ActivityType ActivityType = "Workout"
	YOGA_ActivityType ActivityType = "Yoga"
)
