/*
 * Strava API v3
 *
 * Strava API
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package strava

// A roll-up of metrics pertaining to a set of activities. Values are in seconds and meters.
type ActivityTotal struct {
	// The number of activities considered in this total.
	Count int32 `json:"count,omitempty"`
	// The total distance covered by the considered activities.
	Distance float32 `json:"distance,omitempty"`
	// The total moving time of the considered activities.
	MovingTime int32 `json:"moving_time,omitempty"`
	// The total elapsed time of the considered activities.
	ElapsedTime int32 `json:"elapsed_time,omitempty"`
	// The total elevation gain of the considered activities.
	ElevationGain float32 `json:"elevation_gain,omitempty"`
	// The total number of achievements of the considered activities.
	AchievementCount int32 `json:"achievement_count,omitempty"`
}
