/*
 * Strava API v3
 *
 * Strava API
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package strava

type ExplorerResponse struct {
	// The set of segments matching an explorer request
	Segments []ExplorerSegment `json:"segments,omitempty"`
}
