/*
 * Strava API v3
 *
 * Strava API
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package strava

type Upload struct {
	// The unique identifier of the upload
	Id int64 `json:"id,omitempty"`
	// The external identifier of the upload
	ExternalId string `json:"external_id,omitempty"`
	// The error associated with this upload
	Error_ string `json:"error,omitempty"`
	// The status of this upload
	Status string `json:"status,omitempty"`
	// The identifier of the activity this upload resulted into
	ActivityId int64 `json:"activity_id,omitempty"`
}
