/*
 * Strava API v3
 *
 * Strava API
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package strava

// A union type representing the time spent in a given zone.
type TimedZoneRange struct {
	// The minimum value in the range.
	Min int32 `json:"min,omitempty"`
	// The maximum value in the range.
	Max int32 `json:"max,omitempty"`
	// The number of seconds spent in this zone
	Time int32 `json:"time,omitempty"`
}
