/*
 * Strava API v3
 *
 * Strava API
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package strava

import (
	"time"
)

// A row in a segment leaderboard
type SegmentLeaderboardEntry struct {
	// The public name of the athlete
	AthleteName string `json:"athlete_name,omitempty"`
	// The elapsed of the segment effort associated with this entry
	ElapsedTime int32 `json:"elapsed_time,omitempty"`
	// The moving of the segment effort associated with this entry
	MovingTime int32 `json:"moving_time,omitempty"`
	// The time at which the effort was started.
	StartDate time.Time `json:"start_date,omitempty"`
	// The time at which the effort was started in the local timezone.
	StartDateLocal time.Time `json:"start_date_local,omitempty"`
	// The rank of this entry in the leaderboard
	Rank int32 `json:"rank,omitempty"`
}
