/*
 * Strava API v3
 *
 * Strava API
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package strava

// A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers.
type LatLng struct {
}
