/*
 * Strava API v3
 *
 * Strava API
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package strava

import (
	"time"
)

type Comment struct {
	// The unique identifier of this comment
	Id int64 `json:"id,omitempty"`
	// The identifier of the activity this comment is related to
	ActivityId int64 `json:"activity_id,omitempty"`
	// The content of the comment
	Text string `json:"text,omitempty"`
	Athlete *SummaryAthlete `json:"athlete,omitempty"`
	// The time at which this comment was created.
	CreatedAt time.Time `json:"created_at,omitempty"`
}
