/*
 * Strava API v3
 *
 * Strava API
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package strava

// Stores the exclusive ranges representing zones and the time spent in each.
type TimedZoneDistribution struct {
}
