/*
 * Strava API v3
 *
 * Strava API
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package strava

// Encapsulates the errors that may be returned from the API.
type Fault struct {
	// The set of specific errors associated with this fault, if any.
	Errors []ModelError `json:"errors,omitempty"`
	// The message of the fault.
	Message string `json:"message,omitempty"`
}
